rrt:
  ros__parameters:
    waypoints_path: "/home/meric/f1tenth_ws_mpc_emergency/src/waypoint_generator/src/1104_final.csv"
    waypoints_path_2nd: "/home/meric/f1tenth_ws_mpc_emergency/src/waypoint_generator/src/1104_final.csv"
    scan_topic: "/scan"
    odom_topic: "/pf/pose/odom"
    drive_topic: "/drive"
    interpolation_distance: 0.1
    velocity_percentage: 0.5

    lane_number: 0

    K_p: 0.2
    K_p_obstacle: 0.2
    K_E: 1.0
    K_H: 0.5

    min_lookahead: 0.8 # for larger track
    max_lookahead: 1.5 # lookahead when the car is going around max velocity
    min_lookahead_speed: 1.0
    max_lookahead_speed: 2.0 # approximately the max velocity

    # For when there is an obstacle
    velocity_min: 1.0
    velocity_max: 2.0
    steering_limit: 25.0
    cells_per_meter: 20

waypoint_visualizer_node:
  ros__parameters:
    waypoints_path: "/home/meric/f1tenth_ws_mpc_emergency/src/waypoint_generator/src/1104_final.csv"
