joy_teloep:
  ros_parameters:
    human_control:
          type: topic
          interface_type: ackermann_msgs/msg/AckermannDriveStamped
          topic_name: telop
          deadman_buttons: [4]
          axis_mappings:
            drive-speed:
              axis: 1
              scale: 0.8
              offset: 0.0
            drive-steering_anlge:
              axis: 3
              scale: 0.34
              offset: 0.0
