ackermann_mux:  
  ros__parameters:  
    topics:  
#      emergency_brake:  
#        topic: emergency_brake  
#        timeout: 0.2  
#        priority: 255  
      navigation:  
        topic: drive  
        timeout: 0.5  
        priority: 10  
      joystick:  
        topic: teleop  
        timeout: 0.5  
        priority: 100  
#    locks:  
#      emergency_lock:  
#        topic: emergency_brake_lock  
#        timeout: 0.2  
#        priority: 255  
