particle_filter:
  ros__parameters:
    # topic names
    scan_topic: '/scan'
    odometry_topic: '/odom'
    # range data downsampling
    angle_step: 12
    max_particles: 1500
    squash_factor: 2.5
    # visualization
    viz: 0
    max_viz_particles: 60
    # ray marching method
    range_method: 'rmgpu'
    theta_discretization: 112
    # range data filtering
    max_range: 12.0
    fine_timing: 1
    publish_odom: 1
    # sensor model constants
    z_short: 0.01
    z_max: 0.09
    z_rand: 0.25
    z_hit: 0.65
    sigma_hit: 12.0
    # motion model dispersion constants
    motion_dispersion_x: 0.08
    motion_dispersion_y: 0.04
    motion_dispersion_theta: 0.35
    # sensor model variant, variant 2 good for rmgpu, 3 doesn't work for rmgpu
    rangelib_variant: 2

map_server:
  ros__parameters:
    # assuming map file is in particle_filter/maps
    map: '0523'
